### ISSUE TITLE
Can't connect tp Arduino UNO in the Arduino Lab for Python

### ISSUE THREAD

**Issue by hash207** [arduino/lab-micropython-editor#122]
I've installed the Arduino Lab for MicroPython, then when I tried connecting to the UNO module, the app get stuck, I mean that it doesn't response to me any more and I've to close it and reopen it again, but it didn't work even once 
![Screenshot (12)](https://github.com/arduino/lab-micropython-editor/assets/132669345/aa4b597d-c2b4-497f-bd62-8ec3eb04466e)

**Comment by ubidefeo** [comment]
@hash207 
Arduino UNO does not and cannot run MicroPython.
You need Arduino IDE 2.3.2 to program and upload Arduino boards that only support Arduino C++

**Comment by hash207** [comment]
I didn't know that. 
thanks
