### ISSUE TITLE
UI frozen with spinning wheel saying 'loading files'

### ISSUE THREAD

**Issue by AppsByDavideV** [arduino/lab-micropython-editor#126]
Hello devs,
as per title, interface frozen, lab-micropython-editor version 0.10.0.
How: after the first start where I chose the working files path, I changed the name of the working folders on the PC. Of course the app cannot find the new files path. 
The expected behaviour is to ask for a new path if the previous is invalid, but the software is blocked instead.
![Immagine 2024-04-30 173950](https://github.com/arduino/lab-micropython-editor/assets/17500156/b7c54fe1-e279-4d41-acc7-dc1f5a01ad2e)

Cannot find where that information is stored.

Bye

**Comment by ubidefeo** [comment]
thank you for reporting this, I think it escaped our attention :D 

you can fix it by deleting the settings folder in 
`C:\Users\{USER_NAME}\AppData\Roaming`

**Comment by secretsather** [comment]
Same isue here. I understand the fix (for now) but hope someone is working towards an automatic solution.

**Comment by ubidefeo** [comment]
Fixed in 0.11.0
https://github.com/arduino/lab-micropython-editor/releases/tag/0.11.0
