### ISSUE TITLE
Stuck on Loading when trying to connect Arduino Lab for MicroPython with Esp32

### ISSUE THREAD

**Issue by Zmc18-Robotics** [arduino/lab-micropython-editor#144]
can someone please fix this bug? idk i stuck on loading screen

![Image](https://github.com/user-attachments/assets/923ba23f-c427-4431-8e25-31f76a3b4efd)
![Image](https://github.com/user-attachments/assets/07724b6e-5099-4ee1-bd1d-37ea9d8dd958)

You can see, there are 2 warnings when i opened the devtools

there are no "lib" folder
and also there are no xterm.js.map and xterm-addon-fit.js.map files

pls someone help, where i can find the xterm.js.map and xterm-addon-fit.js.map files?
its so annoying because i cant use my Esp32 for micropython, i dont want to use C/C++ on my esp32

**Comment by ubidefeo** [comment]
@Zmc18-Robotics 

the 2 warnings don't affect the working of the editor.
Usually if it cannot connect to ESP32 it means that it cannot find a REPL prompt or there is some other reason for the board to be locked, possibly a broken file-system (we've seen it on RP2040 but not on ESP32).

Are you sure MicroPython is installed on your ESP32?

**Comment by ubidefeo** [comment]
@Zmc18-Robotics 

this bug has been resolved in the upcoming 0.11.0, to be available next week at the latest

**Comment by Zmc18-Robotics** [comment]
wow thanks!
