### ISSUE TITLE
On MacOS, hidden files are still visible on local storage (.DS_Store file)

### ISSUE THREAD

**Issue by ubidefeo** [arduino/lab-micropython-editor#17]
The dir list filter needs to be updated to filter out hidden files

<img width="302" alt="CleanShot 2022-11-10 at 16 39 07@2x" src="https://user-images.githubusercontent.com/1894487/201139439-337c3e2c-494b-41b2-88f4-361ff5631a80.png">

**Comment by murilopolese** [comment]
This commit (soon to be merged into main) should fix it:  https://github.com/arduino/lab-micropython-editor/commit/6817657f0dc78bd57b38fec6fe170577236b5474

**Comment by murilopolese** [comment]
@ubidefeo Do you think we could close this issue?

**Comment by ubidefeo** [comment]
fixed
