### ISSUE TITLE
Unable to find where to install packages

### ISSUE THREAD

**Issue by ProfessionalGooseChaser** [arduino/lab-micropython-editor#18]
I'm using a a library not included in the packages that come with the IDE. I tried using 'pip install' in the terminal however it throws an error. There was nowhere else that I could find that would give me a usable terminal to install a package. 

I'm sure there's a certain way to format these Issues, but I'm newer to the industry and I wanted to ask for help when using your new product. Thank you so much!

(the package I was trying to instal was osascript)

**Comment by ubidefeo** [comment]
@ProfessionalGooseChaser 
thank you for submitting this issue.

Micropython supports **root** (**/**) and **lib** folder to add modules.
They are findable by any script running based on their location on the board's file-system.

For now the only way is to copy your module to the local filesystem and from there copy the files manually

![CleanShot 2022-11-11 at 09 11 27@2x](https://user-images.githubusercontent.com/1894487/201295672-632b8940-bb53-49b3-ab7f-1450b08806e8.png)

Hope that helps :)

**Comment by ProfessionalGooseChaser** [comment]
Thank you so much for your help! I got the libraries I needed installed.

**Comment by ubidefeo** [comment]
my pleasure 😃
