### ISSUE TITLE
File type extension

### ISSUE THREAD

**Issue by Jeff-Squared** [arduino/lab-micropython-editor#23]
At the moment it is possible to create a file without an extension, save it to disk then upload to the device where it becomes invisible to the user which takes up space in the flash. A new user might not realize this is happening until there is no room to upload a program, perhaps there is a way to force the entry of an extension before saving or uploading.

**Comment by ubidefeo** [comment]
excellent idea, @Jeff-Squared 
maybe enforcing a regexp pattern might do the trick, but we need to handle pattern rejection and some sort of warning feedback on the field

**Comment by Jeff-Squared** [comment]
I am using the app whenever I get the opportunity, I thought it might help a little if I let you know how it looked from a users point of view :o)

**Comment by ubidefeo** [comment]
@Jeff-Squared 
it is now possible to create and list files without extension.

I'll close this issue
thanks
u.
