### ISSUE TITLE
Version 0.6.0 still reports as 0.5.0

### ISSUE THREAD

**Issue by dsssssssss9** [arduino/lab-micropython-editor#31]
Completely fresh version of the of 0.6.0 on a Linux machine
Still reports as 0.5.0

![cropped](https://user-images.githubusercontent.com/30810847/210792322-df079a71-905b-4f68-8cd9-949b61e2fa06.png)

**Comment by ubidefeo** [comment]
hi @dsssssssss9 
thank you so much for this

I made a rookie mistake there hardcoding the version.
Will change it to grab that off the package.json 🙏🏼 

Rest assured, though
 you are running 0.6.0 😬

**Comment by ubidefeo** [comment]
@dsssssssss9 
I went to check the code-base and tested on my machine.
The correct version is reported 🤔 

Which OS are you running?

**Comment by dsssssssss9** [comment]
Ubuntu 20.04 LTS

**Comment by ubidefeo** [comment]
@murilopolese , can you check if the version is wrong on your Linux machine?

**Comment by dsssssssss9** [comment]
any update on this please?

**Comment by ubidefeo** [comment]
@dsssssssss9 
I have not managed to reproduce this issue on Mac or Linux.
I am using Ubuntu 22 on arm64

**Comment by dsssssssss9** [comment]
closed as have completely wiped every trace of all versions & reinstalled from fresh copy of v6 from GitHub - now reports correct version
