### ISSUE TITLE
When clicking "disconnect", the port remains open

### ISSUE THREAD

**Issue by ubidefeo** [arduino/lab-micropython-editor#34]
Until the app is closed, the Serial port is busy.

To reproduce:
- connect to a board
- disconnect
- run `screen /dev/boardPortTTY 115200`

the message received will be 
`Cannot open line '/dev/boardPortTTY' for R/W: Resource busy`

Debugging the app did not bear any fruit.
The disconnection happens correctly when the **Connect** operation is triggered,
otherwise it would not connect to it, I guess.

**Comment by murilopolese** [comment]
I could not reproduce on my Linux machine. What OS are you using?
Maybe it's not really disconnecting or there is a cache on OS level somehow.

**Comment by ubidefeo** [comment]
Mac OS

Let's try and do a live session of debug soon.
I think the binding stays on, and on mac it just reconnects to the same resource

**Comment by ubidefeo** [comment]
For anyone experiencing this, there's a fix and it will be part of 0.8.0

**Comment by ubidefeo** [comment]
fixed
