### ISSUE TITLE
MicroPython not connecting with PICO w

### ISSUE THREAD

**Issue by mpsaju** [arduino/lab-micropython-editor#48]
I am new to PICO and Micropython
I have downloaded and extracted the Arduino Lab for MicroPython and started it. Then I connected a PICO W to the USB port on my laptop (Windows 11) while pressing the Bootsel button as instructed. The PICO has been recognised as an external drive by Windows 11.0
Next I tried the "Connect" button on the Arduino-M.Python ide. A screen with " Refresh" came up and it is not connecting to the PICO W

What should I do to resolve this issue ?

**Comment by mpsaju** [comment]
I find that the same board and setup is running with the normal Arduino ide 2.10 with Raspberry PI PICO W board installed. So I believe I have missed something with the "Arduino Lab for MicroPython" ide. This is making me even more desperate!!

**Comment by ubidefeo** [comment]
Since no further feedback has been provided by @mpsaju , I will close this issue
