### ISSUE TITLE
Release asset naming convention should follow the Arduino asset naming convention

### ISSUE THREAD

**Issue by kittaakos** [arduino/lab-micropython-editor#52]
The release should produce artifacts with the following naming pattern:

```
${APP_NAME}_${APP_VERSION}_{Linux|macOS|Windows}_{ARMv6|ARMv7|ARM64|64bit}.{zip|exe|msi|dmg|AppImage}
```

At least other products follow this convention.

**Comment by ubidefeo** [comment]
thank you @kittaakos 

we have "copied" one of the workflows, but as you know I'm not very well versed in GH actions.
could you help us with a PR, maybe?

thanks
u.

**Comment by kittaakos** [comment]
We must keep `arm64` as is in the filename. I am closing as _won't fix_. See https://github.com/arduino/arduino-ide/issues/2117#issuecomment-1749900052.
