### ISSUE TITLE
It keeps showing that it is connected, but it cannot connect to the device.

### ISSUE THREAD

**Issue by glylsm** [arduino/lab-micropython-editor#59]

**Comment by ubidefeo** [comment]
@glylsm 
we'll need a bit more info about this

- device used
- micropython version (and where you downloaded it from)
- operating system

**Comment by glylsm** [comment]
device used is seeed's WioTerminal,and micropython download at official website,and operating system is windows 10










@lsm
***@***.***







                       
原始邮件
                       
                     

发件人："Ubi de Feo"< ***@***.*** &gt;;

发件时间：2023/8/17 13:37

收件人："arduino/lab-micropython-editor"< ***@***.*** &gt;;

抄送人："glylsm"< ***@***.*** &gt;;"Mention"< ***@***.*** &gt;;

主题：Re: [arduino/lab-micropython-editor] It keeps showing that it isconnected, but it cannot connect to the device. (Issue #59)




 
@glylsm
 we'll need a bit more info about this
  
device used
 
micropython version (and where you downloaded it from)
 
operating system

**Comment by glylsm** [comment]
> 我们需要更多关于这方面的信息。
> 
> * 使用的设备
> * Micropython版本（以及您从何处下载它）
> * 操作系统

device used is seeed's WioTerminal,and micropython download at official website,and operating system is windows 10

**Comment by JonSumpter** [comment]
Hi, yes my RP2040 will not  stay connected. Right now LEDs are flashing. When RP2040 does connect and I do anything (open file, attempt to install micropython, ect) all the LED go dark and only the power LED stay on.
    Here's the twist: I switch USB ports, all the LEDs come on. Above condition happens again.
I'm running "Arduino Lab for Micropython" and trying to install "Micropython Installer" from Arduino

**Comment by ubidefeo** [comment]
This thread highlights an issue with the installed MicroPython version or failure to install it.
Should be traced back to the boards, not the editor, which works with stock MicroPython.
If the manufacturer of your boards forks MicroPython and does not maintain/support it, making sure that a proper REPL is output to the serial port, we cannot handle connections/disconnections to it.

That said, please try version 0.9.1 and let us know

**Comment by ubidefeo** [comment]
closed for lack of feedback
