### ISSUE TITLE
'Disconnected' banner

### ISSUE THREAD

**Issue by AppsByDavideV** [arduino/lab-micropython-editor#61]
Hello,
it would be nice to remove the  yellow 'Disconnected' banner that hides files, so it will be possible to edit them on local folder  without a connected device.

Thanks

**Comment by ubidefeo** [comment]
hi @AppsByDavideV 

Will definitely put this one in the backlog because it can be pretty annoying 😄 

Thank you for the suggestion
u.

**Comment by murilopolese** [comment]
Thank you for your suggestion @AppsByDavideV ! We'll have a look into it. 
As a work around, as soon as you save a local file the banner will disappear.

**Comment by IvanR3D** [comment]
> Hello, it would be nice to remove the yellow 'Disconnected' banner that hides files, so it will be possible to edit them on local folder without a connected device.
> 
> Thanks

It is easy to solve this by increasing the z-index of #panel.open (in the theme.css file) to 10000 (ten thousand). Then the file panel will get over the disconnected message that currently have a z-index of 9999.

**Comment by ubidefeo** [comment]
@AppsByDavideV @IvanR3D 
version 0.9 has a rewritten UI which does not exhibit these annoyances.

Please try it and let us know

**Comment by AppsByDavideV** [comment]
@ubidefeo : I see, nice UI, great!
