### ISSUE TITLE
Escaped characters are removed when saving to board (or copying local>board)

### ISSUE THREAD

**Issue by ubidefeo** [arduino/lab-micropython-editor#8]
I have tried to use an apostrophe in a string 
`print('good ol' times')`
and of course won't work.

If I were to escape that apostrophe it would be like
`print('good ol\' times')`
which works fine while running, but when I save it gets stripped from the source

**Comment by murilopolese** [comment]
This commit (soon to be merged into `main`) should fix it: https://github.com/arduino/lab-micropython-editor/commit/d3b5920f8ca87425c46f0f87178b22849ed30a02

**Comment by murilopolese** [comment]
@ubidefeo Do you think we could close this issue?
